// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WpfApp3.Data;

#nullable disable

namespace WpfApp3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251016223335_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("WpfApp3.Models.MaterialTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LosePercent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MaterialTypes");
                });

            modelBuilder.Entity("WpfApp3.Models.ProductTypes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Coefficient")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");
                });

            modelBuilder.Entity("WpfApp3.Models.ProductWorkshops", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ManufacturingInHours")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkshopId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopId");

                    b.ToTable("ProductWorkshops");
                });

            modelBuilder.Entity("WpfApp3.Models.Products", b =>
                {
                    b.Property<int>("Article")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaterialTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MinimalCost")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Article");

                    b.HasIndex("MaterialTypeId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("WpfApp3.Models.Workshops", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StuffCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkshopType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Workshops");
                });

            modelBuilder.Entity("WpfApp3.Models.ProductWorkshops", b =>
                {
                    b.HasOne("WpfApp3.Models.Workshops", "Workshop")
                        .WithMany("ProductWorkshops")
                        .HasForeignKey("WorkshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workshop");
                });

            modelBuilder.Entity("WpfApp3.Models.Products", b =>
                {
                    b.HasOne("WpfApp3.Models.MaterialTypes", "MaterialType")
                        .WithMany("Products")
                        .HasForeignKey("MaterialTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WpfApp3.Models.ProductTypes", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaterialType");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("WpfApp3.Models.MaterialTypes", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WpfApp3.Models.ProductTypes", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WpfApp3.Models.Workshops", b =>
                {
                    b.Navigation("ProductWorkshops");
                });
#pragma warning restore 612, 618
        }
    }
}
